distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Runtime: 5.7
  perl: 5.6.1
version: 5.7001
