name: Catalyst
version: 5.61
abstract: Catalyst Web Framework
author: Sebastian Riedel
license: perl
distribution_type: module
requires:
  perl: 5.8.1
  UNIVERSAL::require: 0.10
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Class::Inspector: 0
  CGI::Cookie: 0
  File::Modified: 0
  HTML::Entities: 0
  HTTP::Body: 0.5
  HTTP::Headers: 1.59
  HTTP::Request: 0
  HTTP::Response: 0
  HTTP::Request::AsCGI: 0
  LWP::UserAgent: 0
  MIME::Types: 0
  Module::Pluggable::Fast: 0.16
  NEXT: 0
  Path::Class: 0.09
  Scalar::Util: 0
  Template: 0
  Text::SimpleTable: 0
  Test::MockObject: 0
  Time::HiRes: 0
  Tree::Simple: 0
  Tree::Simple::Visitor::FindByPath: 0
  URI: 1.35
  File::Copy::Recursive: 0
  Module::Install::Admin: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
