# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst
version:      5.03
version_from: lib/Catalyst.pm
installdirs:  site
requires:
    CGI::Simple:                   0
    Class::Accessor::Fast:         0
    Class::Data::Inheritable:      0
    HTML::Entities:                0
    HTTP::Daemon:                  0
    HTTP::Headers:                 0
    HTTP::Request:                 0
    HTTP::Response:                0
    LWP::UserAgent:                0
    Module::Pluggable::Fast:       0
    Template:                      0
    Text::ASCIITable:              0
    Tree::Simple:                  0
    Tree::Simple::Visitor::FindByPath: 0
    UNIVERSAL::require:            0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
