---
name: Catalyst
version: 5.49_01
author:
  - 'Sebastian Riedel, C<sri@oook.de>'
abstract: The Elegant MVC Web Application Framework
license: perl
requires:
  CGI::Cookie: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  HTML::Entities: 0
  HTTP::Body: 0
  HTTP::Headers: 1.59
  HTTP::Request: 0
  HTTP::Response: 0
  LWP::UserAgent: 0
  Module::Pluggable::Fast: 0.16
  NEXT: 0
  Path::Class: 0.09
  Scalar::Util: 0
  Template: 0
  Test::MockObject: 0
  Text::ASCIITable: 0.17
  Tree::Simple: 0
  Tree::Simple::Visitor::FindByPath: 0
  UNIVERSAL::require: 0
  URI: 1.35
  URI::Query: 0
  perl: 5.8.1
recommends:
  Catalyst::Engine::Apache: 0
provides:
  Catalyst:
    file: lib/Catalyst.pm
    version: 5.49_01
  Catalyst::Action:
    file: lib/Catalyst/Action.pm
  Catalyst::Base:
    file: lib/Catalyst/Base.pm
  Catalyst::Build:
    file: lib/Catalyst/Build.pm
  Catalyst::Dispatcher:
    file: lib/Catalyst/Dispatcher.pm
  Catalyst::Engine:
    file: lib/Catalyst/Engine.pm
  Catalyst::Engine::CGI:
    file: lib/Catalyst/Engine/CGI.pm
  Catalyst::Engine::FastCGI:
    file: lib/Catalyst/Engine/FastCGI.pm
  Catalyst::Engine::HTTP:
    file: lib/Catalyst/Engine/HTTP.pm
  Catalyst::Engine::Test:
    file: lib/Catalyst/Engine/Test.pm
  Catalyst::Exception:
    file: lib/Catalyst/Exception.pm
  Catalyst::Exception::Base:
    file: lib/Catalyst/Exception.pm
  Catalyst::Helper:
    file: lib/Catalyst/Helper.pm
    version: 0.01
  Catalyst::Log:
    file: lib/Catalyst/Log.pm
  Catalyst::Request:
    file: lib/Catalyst/Request.pm
  Catalyst::Request::Upload:
    file: lib/Catalyst/Request/Upload.pm
  Catalyst::Response:
    file: lib/Catalyst/Response.pm
  Catalyst::Test:
    file: lib/Catalyst/Test.pm
  Catalyst::Utils:
    file: lib/Catalyst/Utils.pm
generated_by: Module::Build version 0.2611
